#!/bin/bash

sudo yum update -y

sudo yum install docker -y

systemctl status docker 
systemctl start docker
systemctl enable docker 

docker run --name docker-jenkins -p 8080:8080 -p 50000:50000 -v /var/jenkins_home jenkins/jenkins:lts

